{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stemjson",
    "module": "stem-runtime-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "stem-runtime-sdk-1.0.0.aar",
          "url": "stem-runtime-sdk-1.0.0.aar",
          "size": 1490648,
          "sha512": "7e9274c5482dfcb29229e7fe017fd05bab77d200bdac5003dea10ee9e5bd0839607d6b8f5a9fbf0c8c935a018ae4be0601a6fc784e7dddb62c48694a15872372",
          "sha256": "9b1d7dca3cd026bcca6c6188f86ac70acd16ac8a62d9854c440aa108b52147c2",
          "sha1": "f7a83822c14ce888772db6ac8041db88e1e54675",
          "md5": "7c2242112893fd4f4eef2c41da292284"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2024.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-compose",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.coil-kt.coil3",
          "module": "coil-network-okhttp",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "stem-runtime-sdk-1.0.0.aar",
          "url": "stem-runtime-sdk-1.0.0.aar",
          "size": 1490648,
          "sha512": "7e9274c5482dfcb29229e7fe017fd05bab77d200bdac5003dea10ee9e5bd0839607d6b8f5a9fbf0c8c935a018ae4be0601a6fc784e7dddb62c48694a15872372",
          "sha256": "9b1d7dca3cd026bcca6c6188f86ac70acd16ac8a62d9854c440aa108b52147c2",
          "sha1": "f7a83822c14ce888772db6ac8041db88e1e54675",
          "md5": "7c2242112893fd4f4eef2c41da292284"
        }
      ]
    }
  ]
}
